
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import { ThemeProvider } from "@/app/context/ThemeContext";
import { Container } from "@/app/components/Container";
import { Providers } from "@/utils/providers";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LosFlix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en" className=" ">

      <body className={`${inter.className} bg-slate-200 dark:bg-black overflow-x-hidden  `}>
        <ThemeProvider>
          
          <Container >

            <header className="">
              <Header />
            </header>
            <Providers>
              
                <main className="container max-w-md ">{children}</main>
            </Providers>
          </Container>
          
        </ThemeProvider>
      </body>

    </html>

  );
}
